
server.port=8080
spring.application.name=param-mart


# ==========================
# MYSQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/parammart_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=9702

allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ==========================
# LOGGING
# ==========================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG



logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=ZmY0YzQwYzQ5ZDI3NzY2NTVlY2Q2M2IwYjRiNjYzZjM5OTg4NzY2N2YxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg=
jwt.expiration=86400000
